### ISSUE TITLE
Rough TODO

### ISSUE THREAD

**Issue by juliancwirko** [xdevguild/nextjs-dapp-template#1]
- ~~migrate the elven-tools-dapp to erdjs 10~~ [done]
- ~~clone and clean the template to be more generic~~ [done]
- ~~add docs (readme)~~ [done]
- then more improvements
  - ~~Ledger auth~~ [done]
  - more React hooks
  - more tooling
  - rethink the backend integration and server-side auth checks, research: https://github.com/ElrondNetwork/native-auth
  - languages/translations support
- then maybe split into separate npm packages, but I am not sure if this is required

**Comment by mariusgrigoras** [comment]
Thank you for working on this @juliancwirko! Do you have any possible estimation for Ledger auth integration?

**Comment by noc2spam** [comment]
This is excellent stuff and was much needed! Thank you Julian for the selfless work.
Looking forward to the ledger auth provider! :)

**Comment by juliancwirko** [comment]
I need to find my old Nano S ;) 
I plan to work on it very soon. I want to start end of this week, maybe on the weekend.

**Comment by juliancwirko** [comment]
Elven Tools Dapp already has it: https://github.com/ElvenTools/elven-tools-dapp 
So it will be implemented here very soon.

**Comment by juliancwirko** [comment]
Ledger HW provider also merged here, available for testing: https://elrond-nextjs-dapp.netlify.app

**Comment by juliancwirko** [comment]
Progress is now tracked here: https://github.com/orgs/ElrondDevGuild/projects/3/views/1. 
The general issues section is still open. Feel free to report everything there.
