### ISSUE TITLE
Ledger Auth problem

### ISSUE THREAD

**Issue by MartySalade** [xdevguild/nextjs-dapp-template#13]
Hi,

I'm having an issue to connect with my ledger while developing a DApp. When I click on the Ledger button to connect it always goes into the first if statement meaning the *await dappProvider.init();* hasn't returned a successful response, so nothing happens except for the console.warn message in the console. 

![image](https://user-images.githubusercontent.com/47866962/194758316-90b36006-c6ef-4e88-b286-4ad3da5a21f1.png)

When I connect myself with the Extansion (or any other login method), logout and then try to reconnect with ledger, it is working fine. Not sure how it really works there ?

**Comment by juliancwirko** [comment]
Hi, thanks for reporting that. I'll take a look as soon as possible. I will also update dependencies.

By the way, have you got any other error messages in the browser's console when connecting the Ledger device?

Also, the best would be if you could prepare a reproduction repository. But first, I will check all on my side.

I think it shouldn't matter, but what is the type of your Ledger? I tested on Ledger Nano S.

**Comment by MartySalade** [comment]
Ledger Nano S as well! 
Ok thanks, let me know if there is any problem. The only message displayed on the browser is the *'Something went wrong trying to sync with the Ledger!'* message

**Comment by juliancwirko** [comment]
Looks good on my side. The piece of code you pasted here should be triggered when you hard refresh the page, not when you log in, so maybe some state refreshes the page before you log in, and the required states are lost. Do you have the same on the demo website? -> 

The reproduction repository would be super helpful.

By the way. I've updated some dependencies, but I think nothing related to HW.
