### ISSUE TITLE
Expose result of await transactionWatcher.awaitCompleted(tx); to callback

### ISSUE THREAD

**Issue by janniksam** [xdevguild/nextjs-dapp-template#15]
In many cases its necessary to know, if a transaction is failing or not.

We already call it here: [sendTxOperations#L27](https://github.com/ElrondDevGuild/nextjs-dapp-template/blob/main/hooks/core/common-helpers/sendTxOperations.ts#L27)

```js
const transactionWatcher = new TransactionWatcher(apiNetworkProvider);
await transactionWatcher.awaitCompleted(tx);
setTransaction(tx);
cb?.({ transaction: tx, pending: false });
```

To be able to deal with the transactions status at a higher level I would suggest something like this:
```js
const transactionWatcher = new TransactionWatcher(apiNetworkProvider);
const txResult = await transactionWatcher.awaitCompleted(tx);
setTransaction(tx);
cb?.({ transaction: tx, pending: false; result: txResult });
```

**Comment by juliancwirko** [comment]
Good point. It may need more work, like global states handling responses from smart contracts, etc. I added it to the todo list: https://github.com/orgs/xdevguild/projects/1. I'll get back to it shortly

**Comment by juliancwirko** [comment]
`useTransaction` and `useScTransaction` now return `txResult`

```
const { pending, triggerTx, transaction, txResult, error } = useTransaction({ cb });
```
