### ISSUE TITLE
Login methods Maiar + Ledger in Web Wallet don't allow to send transactions

### ISSUE THREAD

**Issue by janniksam** [xdevguild/nextjs-dapp-template#16]
If you log into your wallet via WEB WALLET and use either the method Maiar or Ledger, you can't send transactions with that session.

Maiar: Does say "rejected by user"
Ledger: Does give something like BAD REQUEST signature invalid

**Comment by juliancwirko** [comment]
Confirmed something is buggy in such flow. What is interesting is that with PEM, it works ok. I think Web Wallet should keep the same logic for all methods, but it seems that there are differences. Needs some debugging.

Btw. all methods works ok when used directly, not through the Web Wallet.

**Comment by MauricioHernanCabrera** [comment]
any solution?

**Comment by juliancwirko** [comment]
The web wallet problem is a general problem also reported in the dapp-template, linked here. 
And when it comes to the Ledger, I haven't had time to test it yet. I will try today/tomorrow.

**Comment by juliancwirko** [comment]
I've done some debugging for the Ledger through web wallet, but unfortunately, no solution yet. I will do more debugging in the following days.

**Comment by juliancwirko** [comment]
The problem with the web wallet is known and should be resolved in the new version: https://github.com/ElrondNetwork/elrond-sdk-erdjs-web-wallet-provider/issues/9. I'll check the Ledger-related problem with the web wallet after that update. 

Remember that Ledger used directly in the app should work ok.

**Comment by juliancwirko** [comment]
There is a new problem with that: https://github.com/multiversx/mx-sdk-js-web-wallet-provider/issues/24

**Comment by juliancwirko** [comment]
should be ok now, with newest versions of the mx providers and xPortal
