### ISSUE TITLE
iPhone issue

### ISSUE THREAD

**Issue by andrei-ciocan27** [xdevguild/nextjs-dapp-template#28]
Hello, thank you for providing this amazing template and the hooks, it's great overall but I'm facing an iPhone issue when I try to make a transfer of EGLD. Currently I tried payments on all the platforms on devnet, on the iPhone there is a gas fee error at first but even after I increase the gas limit the app keeps hanging in the loading state and the "tester EGLD" doesn't leave my account. On android it works flawlessly. I used xPortal app to connect on both android and iPhone.

**Comment by juliancwirko** [comment]
Hi, thanks for reporting. I'll check it, and I'll get back to you as soon as I can.

**Comment by andrei-ciocan27** [comment]
Hello, I have an update: at first I tested with older Maiar accounts and had the loading issue on iPhone, on the same older accounts it works on android, after creating a new account on xPortal the payment also works on iPhone. It seems to be an issue with the older accounts on iPhone, on android on the same old accounts I can make payments without any problems.

**Comment by juliancwirko** [comment]
Yes, I had a quick look, but it worked for me at https://www.devnet.buildo.dev, which uses the same template and hooks. So, I wanted to test it more later on the weekend. But it is good to know that. I'll see if I can reproduce that. Thanks for the update.
