### ISSUE TITLE
After signing the transaction using Elrond Wallet the information about transaction is somehow gone.

### ISSUE THREAD

**Issue by Alannek1992** [xdevguild/nextjs-dapp-template#6]
Hi Julian,

I m struggling with tracing the transaction when it is signed by elrond wallet. After signing the transaction I am redirected back to the page and although transaction is still pending my state is not updated correctly and CustomTransactionTrigger component is displayed again in this example even though I should still see Pending. When I click on the btn again then it seems the transaction starts to be processed again.

Please excuse me for this very brief code example. But it should demonstrate whats happening. Probably I m doing something wrong. For e.g. maiar wallet this approach works totally fine.

```
const TransactionModel: React.FC = () => {
  const [result, setResult] = useState<{ type: string; content: string }>();
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string>();

  const handleTxCb = useCallback(
    ({ transaction, pending, error }: TransactionCb) => {
      if (transaction) {
        setResult({ type: "tx", content: transaction.getHash().hex() });
        setPending(false);
        setError(undefined);
      }
      if (pending) {
        setPending(true);
        setError(undefined);
        setResult(undefined);
      }
      if (error) {
        setError(error);
        setPending(false);
        setResult(undefined);
      }
    },
    []
  );

  if (pending) {
    return <h1>TRANSACTION PENDING</h1>;
}

   if (result) {
return <h1>TRANSACTION RESULT</h1>
}

return <CustomTransactionTrigger />;
};


const CustomTransactionTrigger : React.FC<> = ({
  cb,
}) => {
  const { pending, triggerTx, transaction, error } = useScMultiESDTTransaction({
    cb
  });
  const handleSendTx = useCallback(
    (membership: SaleMembershipIf) => {
      const payload = TransactionPayload.contractCall()
        .setFunction(new ContractFunction("MultiESDTNFTTransfer"))
        .setArgs([
          new AddressValue(
            new Address(process.env.NEXT_PUBLIC_SC_ADDRESS as string)
          ),
          new U32Value(2),
          BytesValue.fromUTF8(process.env.NEXT_PUBLIC_WEGLD_TOKEN_ID as string),
          new U64Value(0),
          new BigUIntValue(new BigNumber(egldPrice)),
          BytesValue.fromUTF8(process.env.NEXT_PUBLIC_ELRD_TOKEN_ID as string),
          new U64Value(0),
          new BigUIntValue(new BigNumber(elrdPrice)),
          BytesValue.fromUTF8(BUY_CARD_ENDPOINT),
        ])
        .build();

      triggerTx({
        receiver: address,
        gasLimit: 14000000,
        data: payload,
      });
    },
    [triggerTx]
  );

  return <button onClick={handleSendTx}>trigger</button>;
}
```

**Comment by Alannek1992** [comment]
Damn, I still cannot figure that out. It looks like that after signing the transaction via Elrond Web Wallet and redirecting back to my website the transaction status is not pending anymore.

**Comment by Alannek1992** [comment]
Apparently it looks like the Component must be in the end wrapped in the Authenticated wrapper to ensure proper re-rendering. Otherwise it does not work.

**Comment by Alannek1992** [comment]
Somehow it makes sense and it works correctly. Probably the design I made is not the perfect one. I am trying to present some content to use no matter whether they are connected or not.

But in case they want to interact with the content then they must be connected. If I would simple put the content into <Authenticated> then it would not be visible and not presentable.

**Comment by juliancwirko** [comment]
Transactions require Authenticated context, but queries should work, so you should be able to do the sc query without it. 
I think I don't see any other use case. You would want to do transactions or queries, right?

**Comment by juliancwirko** [comment]
btw `Authenticated` component is just an abstraction, you would need to wait for :

```
const { isLoggingIn, isLoggedIn } = useLoggingIn();
```

to get whole auth setup and context

**Comment by Alannek1992** [comment]
Yes, I you re totally right. Especially after login via web wallet the setup must be again loaded. I did not know that :)
